### ISSUE TITLE
Benchmark not updated

### ISSUE THREAD

**Issue by ghost** [AdobeDocs/commerce-operations.fr-FR#2]
Issue in ./help/implementation-playbook/infrastructure/performance/benchmarks.md

Should be 2M page views per hours and 208k orders per hours !

**Comment by yanlicao** [comment]
Dear @mlds-adobe , thanks for your feedback, we are verifying and will update this page accordingly once confirmed.

**Comment by jeff-matthews** [comment]
Thanks for the report @mlds-adobe. You are correct. We're updating the page and will close this issue when complete.

**Comment by jeff-matthews** [comment]
Verified with Product Manager and updated the source: https://github.com/AdobeDocs/commerce-operations.en/commit/f5c890e9c714782d92db52b0d62d06118dcdb180.

Updates will be published today during the next deployment window.
