### ISSUE TITLE
Version 2.4.5

### ISSUE THREAD

**Issue by lcanonge** [AdobeDocs/commerce-operations.fr-FR#3]
https://experienceleague.adobe.com/fr/docs/commerce-operations/release/versions#20
Version 2.4.5 
sentence is :
2.4.5
La prise en charge de la version 2.4.5 se termine en août 9 mars 2025.
Is it august or march 2025 ?

**Comment by jonsamhudec** [comment]
@lcanonge thank you for your feedback. This is being reviewed and tracked in G11N-17616.

**Comment by jonsamhudec** [comment]
French page currently contains only machine translation. Referring to English page, correct meaning is: "La prise en charge de la version 2.4.5 se termine le 9 août 2025."

**Comment by jonsamhudec** [comment]
Page was updated and published.
